version: '3'
services:
  app:
    build:
      context: ../home-automation-app
      dockerfile: Dockerfile
    env_file:
     - .env.home_automation_app
    ports:
     - "8000:8000"
    restart: always
