version: '3.8'
services:
  app:
    build:
      context: ../home-automation-app
      dockerfile: Dockerfile
    env_file:
     - .env.home_automation_app
    volumes:
      - ./:/usr/src/app
    ports:
     - "8000:8000"
    restart: always
